LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= sunxi-gpio.c util_gpio.c

LOCAL_MODULE:= gpio-service 

LOCAL_FORCE_STATIC_EXECUTABLE := true


LOCAL_STATIC_LIBRARIES := libc 

LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_MODULE_TAGS := debug

include $(BUILD_EXECUTABLE)
